-- liquibase formatted sql
-- changeset iOvcharenko:1
CREATE TYPE work_description AS ENUM (
    'MIXING',
    'MASTERING',
    'PRODUCING',
    'EDITING',
    'WRITING'
    );

CREATE TABLE IF NOT EXISTS request
(
    request_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_name     varchar(128)             not null,
    band_name        varchar(128)             not null,
    count_of_track   bigint                   not null,
    total_amount     decimal                  null,
    deadline         timestamp with time zone null,
    multitrack_link  text                     not null,
    band_email       varchar(128)             not null,
    work_description work_description[]       null,
    request_status   varchar(64)
);

create table if not exists release
(
    release_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_name           varchar(128)             not null,
    release_name        varchar(128)             null,
    work_description    work_description[]       null,
    album_cover_link    text                     null,
    social_network_link text                     null,
    count_of_track      bigint                   not null,
    release_dttm        timestamp with time zone null,
    music_label         varchar(128)             null,
    genre               varchar(64)              not null,
    request_id          bigint                   not null
);

alter table release
    add constraint fk_release_for_request foreign key (request_id)
        references request (request_id)
        on delete restrict on update restrict;

comment on table release is
    'Таблица релизов';
comment on column release.release_id is
    'Ид релиза';
comment on column release.band_name is
    'Название группы';
comment on column release.work_description is
    'Пожелания по звуку, описание работы';
comment on column release.album_cover_link is
    'Ссылка на обложку релиза';
comment on column release.social_network_link is
    'Ссылка на релиз';
comment on column release.count_of_track is
    'Количество треков';
comment on column release.release_dttm is
    'Дата релиза';
comment on column release.music_label is
    'Лейбл на котором издается релиз';
comment on column release.genre is
    'Жанр релиза';

create table if not exists price
(
    price_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mixing          numeric null,
    mastering       numeric null,
    editing         numeric null,
    producing       numeric null,
    discount        numeric null,
    number_of_songs bigint  null,
    request_id      bigint  not null
);
comment on table price is
    'Таблица расчета цены за работу';
comment on column price.price_id is
    'Ид цены';
comment on column price.mixing is
    'Цена сведения';
comment on column price.mastering is
    'Цена мастеринга';
comment on column price.editing is
    'Цена редактирования';
comment on column price.producing is
    'Цена продюсирования';
comment on column price.discount is
    'Скидка в процентах';
comment on column price.number_of_songs is
    'Количество песен';


alter table price
    add constraint fk_price_for_request foreign key (request_id)
        references request (request_id)
        on delete restrict on update restrict;

create table if not exists studio
(
    studio_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_name         varchar(128) not null,
    studio_place        text         null,
    social_network_link text         null
);
comment on table studio is
    'Таблица студии на которой записывался инструмент';
comment on column studio.studio_name is
    'Название студии';
comment on column studio.studio_place is
    'Местоположение студии';
comment on column studio.social_network_link is
    'Ссылка на студию';


create table if not exists instrument
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_property varchar(128) not null,
    instrument_model    varchar(128) null,
    instrument_img      text         null,
    type                VARCHAR(50)  not null,
    studio_id           bigint       not null,
    release_id          bigint       not null
);
comment on table instrument is
    'Таблица остальных инструментов';
comment on column instrument.instrument_property is
    'характеристика инструмента, например перкуссия или струнный';
comment on column instrument.instrument_model is
    'Модель инструмента';
comment on column instrument.instrument_img is
    'Скрин или фото цепочки эффектов инструмента';

alter table instrument
    add constraint fk_instrument_for_release foreign key (release_id)
        references release (release_id)
        on delete restrict on update restrict,
    add constraint fk_instrument_for_studio foreign key (studio_id)
        references studio (studio_id)
        on delete cascade on update cascade;

create table if not exists drums
(
    id      BIGINT PRIMARY KEY,
    drums_mics    text   null,
    FOREIGN KEY (id) REFERENCES instrument(id) ON DELETE CASCADE
);


comment on table drums is
    'Таблица информации о барабанах';
comment on column drums.id is
    'Ид барабанов';
comment on column drums.drums_mics is
    'Микрофоны поканально';

create table if not exists guitar
(
    id     BIGINT PRIMARY KEY,
    signal_chain  text   null,
    FOREIGN KEY (id) REFERENCES instrument(id) ON DELETE CASCADE
);

comment on table guitar is
    'Табица гитар';
comment on column guitar.id is
    'Ид гитары';

create table if not exists vocal
(
    id        BIGINT PRIMARY KEY,
    vocal_technique varchar(128) null,
    vocal_mic       varchar(128) null,
    FOREIGN KEY (id) REFERENCES instrument(id) ON DELETE CASCADE
);

comment on table vocal is
    'Таблица вокалов';
comment on column vocal.id is
    'Id вокалов';
comment on column vocal.vocal_technique is
    'Техника исполнения';
comment on column vocal.vocal_mic is
    'Какой микрофон использовался на записи';

create table if not exists other_instrument
(
    id bigint primary key,
    preset              text   null,
    FOREIGN KEY (id) REFERENCES instrument(id) ON DELETE CASCADE
);

